// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── Web ───────────────────────────────────────────────────────────────────
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs1uz_dfod3gh0I9m2hpUVcxUhOIBV6XQ',
    appId: '1:809612402395:web:48c6ceb41f49c3ed07b6fe',
    messagingSenderId: '809612402395',
    projectId: 'cpapp-ace05',
    storageBucket: 'cpapp-ace05.firebasestorage.app',
    authDomain: 'cpapp-ace05.firebaseapp.com',
  );

  // ── Android ───────────────────────────────────────────────────────────────
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs1uz_dfod3gh0I9m2hpUVcxUhOIBV6XQ',
    appId: '1:809612402395:android:e11755206d72379f07b6fe',
    messagingSenderId: '809612402395',
    projectId: 'cpapp-ace05',
    storageBucket: 'cpapp-ace05.firebasestorage.app',
  );

  // ── iOS ───────────────────────────────────────────────────────────────────
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: '809612402395',
    projectId: 'cpapp-ace05',
    storageBucket: 'cpapp-ace05.firebasestorage.app',
    iosBundleId: 'com.digiprop.cpapp',
  );
}
