// Run: node scripts/seed_listings.js
// Seeds Firestore with dummy listings that have propertyType set.

const { initializeApp } = require('firebase-admin/app');
const { getFirestore, Timestamp, FieldValue } = require('firebase-admin/firestore');
const { credential } = require('firebase-admin');

initializeApp({ projectId: 'cpapp-ace05' });

const db = getFirestore();

const listings = [
  {
    brokerUid:       'seed-broker-1',
    brokerName:      'Rajesh Sharma',
    brokerPhotoUrl:  null,
    brokerPhone:     '+91 98765 43210',
    category:        'sale',
    propertyType:    'bhk2',
    city:            'Mumbai',
    location:        'Andheri West',
    area:            850,
    price:           9500000,
    description:     'Spacious 2 BHK in prime Andheri West location. Ready to move. 24/7 security, parking included.',
    heroImageUrl:    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    additionalImageUrls: [],
    posterUrl:       null,
    status:          'active',
    likesCount:      12,
    commentsCount:   3,
    viewsCount:      45,
    createdAt:       Timestamp.fromDate(new Date(Date.now() - 2 * 60 * 60 * 1000)),
  },
  {
    brokerUid:       'seed-broker-2',
    brokerName:      'Priya Mehta',
    brokerPhotoUrl:  null,
    brokerPhone:     '+91 87654 32109',
    category:        'rent',
    propertyType:    'bhk3',
    city:            'Pune',
    location:        'Baner',
    area:            1400,
    price:           45000,
    description:     '3 BHK semi-furnished flat available for rent. Gym, swimming pool, covered parking.',
    heroImageUrl:    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    additionalImageUrls: [],
    posterUrl:       null,
    status:          'active',
    likesCount:      8,
    commentsCount:   1,
    viewsCount:      30,
    createdAt:       Timestamp.fromDate(new Date(Date.now() - 5 * 60 * 60 * 1000)),
  },
  {
    brokerUid:       'seed-broker-3',
    brokerName:      'Amit Patel',
    brokerPhotoUrl:  null,
    brokerPhone:     '+91 76543 21098',
    category:        'sale',
    propertyType:    'plot',
    city:            'Ahmedabad',
    location:        'SG Highway',
    area:            2400,
    price:           7200000,
    description:     'Corner plot in gated township. All amenities nearby. Clear title. Immediate registration.',
    heroImageUrl:    'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    additionalImageUrls: [],
    posterUrl:       null,
    status:          'active',
    likesCount:      5,
    commentsCount:   0,
    viewsCount:      18,
    createdAt:       Timestamp.fromDate(new Date(Date.now() - 1 * 24 * 60 * 60 * 1000)),
  },
  {
    brokerUid:       'seed-broker-4',
    brokerName:      'Sneha Joshi',
    brokerPhotoUrl:  null,
    brokerPhone:     '+91 65432 10987',
    category:        'sale',
    propertyType:    'villa',
    city:            'Bangalore',
    location:        'Whitefield',
    area:            3200,
    price:           28000000,
    description:     'Luxurious independent villa with private pool. 4 bedrooms, home theatre, modular kitchen.',
    heroImageUrl:    'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800',
    additionalImageUrls: [],
    posterUrl:       null,
    status:          'active',
    likesCount:      24,
    commentsCount:   7,
    viewsCount:      110,
    createdAt:       Timestamp.fromDate(new Date(Date.now() - 3 * 60 * 60 * 1000)),
  },
  {
    brokerUid:       'seed-broker-5',
    brokerName:      'Karan Verma',
    brokerPhotoUrl:  null,
    brokerPhone:     '+91 54321 09876',
    category:        'rent',
    propertyType:    'studio',
    city:            'Hyderabad',
    location:        'Hitech City',
    area:            480,
    price:           22000,
    description:     'Modern studio apartment fully furnished. Walking distance to tech park. Ideal for IT professionals.',
    heroImageUrl:    'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    additionalImageUrls: [],
    posterUrl:       null,
    status:          'active',
    likesCount:      15,
    commentsCount:   2,
    viewsCount:      62,
    createdAt:       Timestamp.fromDate(new Date(Date.now() - 30 * 60 * 1000)),
  },
  {
    brokerUid:       'seed-broker-6',
    brokerName:      'Deepak Nair',
    brokerPhotoUrl:  null,
    brokerPhone:     '+91 43210 98765',
    category:        'barter',
    propertyType:    'shopOffice',
    city:            'Chennai',
    location:        'Anna Nagar',
    area:            600,
    price:           12000000,
    description:     'Commercial space in high footfall area. Ground floor. Great for retail or office. Open for barter.',
    heroImageUrl:    'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
    additionalImageUrls: [],
    posterUrl:       null,
    status:          'active',
    likesCount:      6,
    commentsCount:   0,
    viewsCount:      27,
    createdAt:       Timestamp.fromDate(new Date(Date.now() - 2 * 24 * 60 * 60 * 1000)),
  },
  {
    brokerUid:       'seed-broker-7',
    brokerName:      'Meera Kapoor',
    brokerPhotoUrl:  null,
    brokerPhone:     '+91 32109 87654',
    category:        'sale',
    propertyType:    'bhk1',
    city:            'Delhi',
    location:        'Dwarka Sector 12',
    area:            520,
    price:           5800000,
    description:     'Cozy 1 BHK in well-maintained society. Metro connectivity. Suitable for first-time buyers.',
    heroImageUrl:    'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
    additionalImageUrls: [],
    posterUrl:       null,
    status:          'active',
    likesCount:      9,
    commentsCount:   1,
    viewsCount:      38,
    createdAt:       Timestamp.fromDate(new Date(Date.now() - 7 * 60 * 60 * 1000)),
  },
  {
    brokerUid:       'seed-broker-8',
    brokerName:      'Rohit Singh',
    brokerPhotoUrl:  null,
    brokerPhone:     '+91 21098 76543',
    category:        'sale',
    propertyType:    'penthouse',
    city:            'Mumbai',
    location:        'Lower Parel',
    area:            4500,
    price:           75000000,
    description:     'Sky-high penthouse with panoramic sea view. Private terrace, jacuzzi, smart home automation.',
    heroImageUrl:    'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
    additionalImageUrls: [],
    posterUrl:       null,
    status:          'active',
    likesCount:      43,
    commentsCount:   12,
    viewsCount:      210,
    createdAt:       Timestamp.fromDate(new Date(Date.now() - 4 * 60 * 60 * 1000)),
  },
];

async function seed() {
  console.log(`Seeding ${listings.length} listings to Firestore...`);
  const col = db.collection('listings');
  for (const l of listings) {
    const ref = col.doc();
    await ref.set({ ...l, id: ref.id, updatedAt: FieldValue.serverTimestamp() });
    console.log(`  ✓ ${l.propertyType.padEnd(12)} | ${l.brokerName} | ${l.city}`);
  }
  console.log('Done!');
  process.exit(0);
}

seed().catch(e => { console.error(e); process.exit(1); });
